import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DarkModeToggle from "./components/darkmodetoggle"; // import the DarkModeToggle component
import Navbar from "./components/Navbar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';


const HM = localFont({
  src: "./fonts/HelloMorgan.ttf",
  variable: "--font-HM",
});

const NooksScriptRegular = localFont({
  src: "./fonts/TT-Nooks-Script-Trial-Regular.ttf",
  variable: "--font-NooksScriptRegular",
});

const NooksScriptBold = localFont({
  src: "./fonts/TT-Nooks-Script-Trial-Bold.ttf",
  variable: "--font-NooksScriptBold",
});

const AdonisRegular = localFont({
  src: "./fonts/fontspring-demo-adn55.otf",
  variable: "--font-AdonisRegular",
});

const GentlemensScript = localFont({
  src: "./fonts/GentlemensScript.otf",
  variable: "--font-Gentlemens",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      {/* Ensuring viewport scaling works correctly on all devices */}
      <head>
      <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
      <script src="https://www.instagram.com/embed.js" />

      </head>


      {/* Set the class to 'dark' to apply dark mode styles globally */}
      <body className={`${HM.variable} ${NooksScriptBold.variable} ${NooksScriptRegular.variable} ${AdonisRegular.variable} ${GentlemensScript.variable} antialiased`}>
      <AppRouterCacheProvider>
        <Navbar />
        {/* Include the DarkModeToggle button for theme toggling */}
        {children}
      </AppRouterCacheProvider>
      </body>
    </html>
  );
}
