import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import Script from "next/script";


const HM = localFont({
  src: "./fonts/HelloMorgan.ttf",
  variable: "--font-HM",
});

const NooksScriptRegular = localFont({
  src: "./fonts/TT-Nooks-Script-Trial-Regular.ttf",
  variable: "--font-NooksScriptRegular",
});

const NooksScriptBold = localFont({
  src: "./fonts/TT-Nooks-Script-Trial-Bold.ttf",
  variable: "--font-NooksScriptBold",
});

const AdonisRegular = localFont({
  src: "./fonts/fontspring-demo-adn55.otf",
  variable: "--font-AdonisRegular",
});

const GentlemensScript = localFont({
  src: "./fonts/GentlemensScript.otf",
  variable: "--font-Gentlemens",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
        <Script
          src="https://www.instagram.com/embed.js"
          strategy="afterInteractive" // Load script after the page is interactive
        />
      </head>

      <body
        className={`${
          HM.variable
        } ${NooksScriptBold.variable} ${NooksScriptRegular.variable} ${AdonisRegular.variable} ${GentlemensScript.variable} antialiased`}
      >
        <AppRouterCacheProvider>
          <Navbar />
          {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
